# Generated by Django 4.1.4 on 2022-12-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_video_path_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(blank=True, choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete')], max_length=16),
        ),
    ]
